#!/bin/sh
dRunning=$(docker ps -q | wc -l)
dExited=$(docker ps -aq --filter status=exited | wc -l)
dImages=$(docker images -q | wc -l)
dServices=$(docker service ls -q | wc -l)
echo
echo "## DOCKER STATS #################"
echo "#"
echo "# $dRunning containers running."
echo "# $dExited containers exited."
echo "# $dImages images."
echo "#"
echo "## SWARM #######################"
echo "#"
echo "# $dServices services running."
echo "#"
echo "################################"
